const TRANSLATIONS = {
    "en": {
        "welcome": "Welcome to RentArena Zero Brokerage Rental",
        "tagline": "Skip the broker. Rent direct-from-owner properties with zero brokerage fee.",
        "apartment_not_found": "Apartment with ID {id} was not found.",
        "building_not_found": "Building with ID {id} was not found.",
        "occupancy_rate_title": "Occupancy and Rental Analysis",
        "total_apartments": "Total Apartments",
        "occupied_apartments": "Occupied Apartments",
        "vacant_apartments": "Vacant Apartments",
        "occupancy_rate": "Occupancy Rate",
        "success": "Request completed successfully",
        "summary": "This report lists total apartments, highlighting occupied vs. vacant units, calculating overall occupancy rate with zero brokerage fees.",
        "owner_login": "Owner Login",
        "manager_login": "Property Manager Login",
        "tenant_login": "Tenant Login",
        "owner_reg": "Owner Registration",
        "tenant_reg": "Tenant Registration",
        "dashboard": "Dashboard",
        "logout": "Logout",
        "buildings": "Buildings",
        "apartments": "Apartments",
        "tenants": "Tenants",
        "managers": "Property Managers",
        "messages": "Messages",
        "events": "Events",
        "appointments": "Appointments",
        "profile": "Profile",
        "actions": "Actions",
        "edit": "Edit",
        "delete": "Delete",
        "create": "Create",
        "save": "Save",
        "cancel": "Cancel",
        "loading": "Loading...",
        "no_records": "No records found.",
        "email": "Email",
        "password": "Password",
        "phone": "Phone Number",
        "name": "Name",
        "address": "Address",
        "city": "City",
        "province": "Province",
        "postal_code": "Postal Code",
        "price": "Price",
        "rooms": "Rooms",
        "status": "Status",
        "description": "Description",
        "date": "Date",
        "apartment_card_desc": "Browse and explore direct owner apartments.",
        "apartments_flats": "Apartments & Flats",
        "apartments_flats_desc": "1BHK, 2BHK, 3BHK, Studio Apartments",
        "independent_houses": "Independent Houses & Villas",
        "independent_houses_desc": "Villas, Duplexes, Row Houses, Independent Homes",
        "independent_houses_coming": "Independent Houses & Villas feature is coming soon!",
        "commercial_properties": "Commercial Properties",
        "commercial_properties_desc": "Offices, Shops, Showrooms, Co-working Spaces",
        "commercial_properties_coming": "Commercial Properties feature is coming soon!",
        "land_plots": "Land & Plots",
        "land_plots_desc": "Residential Plots, Commercial Plots, Agricultural Land",
        "land_plots_coming": "Land & Plots feature is coming soon!",
        "appointment_booked_notification": "Appointment booked for {date}: {desc}"
    },
    "fr": {
        "welcome": "Bienvenue chez RentArena - Location Sans Commission",
        "tagline": "Évitez le courtier. Connectez-vous directement aux propriétaires.",
        "apartment_not_found": "L'appartement avec l'identifiant {id} n'a pas été trouvé.",
        "building_not_found": "Le bâtiment avec l'identifiant {id} n'a pas été trouvé.",
        "occupancy_rate_title": "Analyse d'occupation et de location",
        "total_apartments": "Nombre total d'appartements",
        "occupied_apartments": "Appartements occupés",
        "vacant_apartments": "Appartements vacants",
        "occupancy_rate": "Taux d'occupation",
        "success": "Requête complétée avec succès",
        "summary": "Ce rapport répertorie le nombre total d'appartements, en indiquant combien sont actuellement occupés ou vacants, et en calculant le taux d'occupation global.",
        "owner_login": "Connexion Propriétaire",
        "manager_login": "Connexion Gestionnaire de Propriété",
        "tenant_login": "Connexion Locataire",
        "owner_reg": "Enregistrement Propriétaire",
        "tenant_reg": "Enregistrement Locataire",
        "dashboard": "Tableau de Bord",
        "logout": "Déconnexion",
        "buildings": "Bâtiments",
        "apartments": "Appartements",
        "tenants": "Locataires",
        "managers": "Gestionnaires de Propriété",
        "messages": "Messages",
        "events": "Événements",
        "appointments": "Rendez-vous",
        "profile": "Profil",
        "actions": "Actions",
        "edit": "Modifier",
        "delete": "Supprimer",
        "create": "Créer",
        "save": "Enregistrer",
        "cancel": "Annuler",
        "loading": "Chargement...",
        "no_records": "Aucun enregistrement trouvé.",
        "email": "Email",
        "password": "Mot de passe",
        "phone": "Téléphone",
        "name": "Nom",
        "address": "Adresse",
        "city": "Ville",
        "province": "Province",
        "postal_code": "Code Postal",
        "price": "Prix",
        "rooms": "Pièces",
        "status": "Statut",
        "description": "Description",
        "date": "Date",
        "apartment_card_desc": "Parcourez et explorez les appartements en direct du propriétaire.",
        "apartments_flats": "Appartements & Appartements",
        "apartments_flats_desc": "1BHK, 2BHK, 3BHK, Studios",
        "independent_houses": "Maisons Individuelles & Villas",
        "independent_houses_desc": "Villas, Duplex, Maisons de Ville, Maisons Individuelles",
        "independent_houses_coming": "La fonctionnalité Maisons Individuelles & Villas sera bientôt disponible!",
        "commercial_properties": "Propriétés Commerciales",
        "commercial_properties_desc": "Bureaux, Boutiques, Showrooms, Espaces de Co-working",
        "commercial_properties_coming": "La fonctionnalité Propriétés Commerciales sera bientôt disponible!",
        "land_plots": "Terrains & Lots",
        "land_plots_desc": "Terrains Résidentiels, Commerciaux, Terres Agricoles",
        "land_plots_coming": "La fonctionnalité Terrains & Lots sera bientôt disponible!",
        "appointment_booked_notification": "Rendez-vous réservé pour {date}: {desc}"
    },
    "vi": {
        "welcome": "Chào mừng đến với RentArena - Thuê nhà Không môi giới",
        "tagline": "Bỏ qua môi giới. Kết nối trực tiếp với chủ nhà. Không phí môi giới.",
        "apartment_not_found": "Không tìm thấy căn hộ có mã số {id}.",
        "building_not_found": "Không tìm thấy tòa nhà có mã số {id}.",
        "occupancy_rate_title": "Phân tích Tỷ lệ Lấp đầy và Cho thuê",
        "total_apartments": "Tổng số căn hộ",
        "occupied_apartments": "Căn hộ đã cho thuê",
        "vacant_apartments": "Căn hộ trống",
        "occupancy_rate": "Tỷ lệ lấp đầy",
        "success": "Yêu cầu đã được thực hiện thành công",
        "summary": "Báo cáo này liệt kê tổng số căn hộ, nêu bật số lượng căn hộ hiện đang có người ở so với căn hộ trống và tính tỷ lệ lấp đầy tổng thể.",
        "owner_login": "Đăng nhập Chủ nhà",
        "manager_login": "Đăng nhập Quản lý Bất động sản",
        "tenant_login": "Đăng nhập Người thuê",
        "owner_reg": "Đăng ký Chủ nhà",
        "tenant_reg": "Đăng ký Người thuê",
        "dashboard": "Bảng điều khiển",
        "logout": "Đăng xuất",
        "buildings": "Tòa nhà",
        "apartments": "Căn hộ",
        "tenants": "Người thuê",
        "managers": "Quản lý Bất động sản",
        "messages": "Tin nhắn",
        "events": "Sự kiện",
        "appointments": "Lịch hẹn",
        "profile": "Hồ sơ",
        "actions": "Hành động",
        "edit": "Sửa",
        "delete": "Xóa",
        "create": "Tạo mới",
        "save": "Lưu",
        "cancel": "Hủy bỏ",
        "loading": "Đang tải...",
        "no_records": "Không có dữ liệu.",
        "email": "Email",
        "password": "Mật khẩu",
        "phone": "Số điện thoại",
        "name": "Họ và tên",
        "address": "Địa chỉ",
        "city": "Thành phố",
        "province": "Tỉnh/Thành",
        "postal_code": "Mã bưu điện",
        "price": "Giá thuê",
        "rooms": "Số phòng",
        "status": "Trạng thái",
        "description": "Mô tả",
        "date": "Ngày hẹn",
        "apartment_card_desc": "Duyệt và khám phá các căn hộ chính chủ.",
        "apartments_flats": "Căn hộ & Chung cư",
        "apartments_flats_desc": "Căn hộ 1BHK, 2BHK, 3BHK, Căn hộ Studio",
        "independent_houses": "Nhà riêng & Biệt thự",
        "independent_houses_desc": "Biệt thự, Nhà thông tầng, Nhà liền kề, Nhà độc lập",
        "independent_houses_coming": "Tính năng Nhà riêng & Biệt thự sắp ra mắt!",
        "commercial_properties": "Bất động sản Thương mại",
        "commercial_properties_desc": "Văn phòng, Cửa hàng, Phòng trưng bày, Không gian làm việc chung",
        "commercial_properties_coming": "Tính năng Bất động sản Thương mại sắp ra mắt!",
        "land_plots": "Đất nền & Lô đất",
        "land_plots_desc": "Đất nền dự án, Đất thương mại, Đất nông nghiệp",
        "land_plots_coming": "Tính năng Đất nền & Lô đất sắp ra mắt!",
        "appointment_booked_notification": "Lịch hẹn được đặt vào {date}: {desc}"
    },
    "es": {
        "welcome": "Bienvenido a RentArena - Alquiler Sin Intermediarios",
        "tagline": "Evite al corredor. Conéctese directamente con los propietarios. Cero comisión.",
        "apartment_not_found": "No se encontró el apartamento con ID {id}.",
        "building_not_found": "No se encontró el edificio con ID {id}.",
        "occupancy_rate_title": "Análisis de Ocupación y Alquiler",
        "total_apartments": "Total de Apartamentos",
        "occupied_apartments": "Apartamentos Ocupados",
        "vacant_apartments": "Apartamentos Vacantes",
        "occupancy_rate": "Tasa de Ocupación",
        "success": "Solicitud completada con éxito",
        "summary": "Este informe enumera el número total de apartamentos, destacando cuántos están ocupados actualmente en comparación con los vacíos, y calculando la tasa de ocupación general.",
        "owner_login": "Iniciar Propietario",
        "manager_login": "Iniciar Administrador de la Propiedad",
        "tenant_login": "Iniciar Inquilino",
        "owner_reg": "Registro Propietario",
        "tenant_reg": "Registro Inquilino",
        "dashboard": "Tablero de Control",
        "logout": "Cerrar sesión",
        "buildings": "Edificios",
        "apartments": "Apartamentos",
        "tenants": "Inquilinos",
        "managers": "Administradores de la Propiedad",
        "messages": "Mensajes",
        "events": "Eventos",
        "appointments": "Citas",
        "profile": "Perfil",
        "actions": "Acciones",
        "edit": "Editar",
        "delete": "Eliminar",
        "create": "Crear",
        "save": "Guardar",
        "cancel": "Cancelar",
        "loading": "Cargando...",
        "no_records": "No se encontraron registros.",
        "email": "Email",
        "password": "Contraseña",
        "phone": "Teléfono",
        "name": "Nombre",
        "address": "Dirección",
        "city": "Ciudad",
        "province": "Provincia",
        "postal_code": "Código Postal",
        "price": "Precio",
        "rooms": "Habitaciones",
        "status": "Estado",
        "description": "Descripción",
        "date": "Fecha",
        "apartment_card_desc": "Busque y explore apartamentos de propietarios directos.",
        "apartments_flats": "Apartamentos y Pisos",
        "apartments_flats_desc": "Apartamentos de 1BHK, 2BHK, 3BHK, Estudios",
        "independent_houses": "Casas Independientes y Villas",
        "independent_houses_desc": "Villas, Dúplex, Casas Adosadas, Casas Independientes",
        "independent_houses_coming": "¡La función de Casas Independientes y Villas estará disponible próximamente!",
        "commercial_properties": "Propiedades Comerciales",
        "commercial_properties_desc": "Oficinas, Tiendas, Showrooms, Espacios de Co-working",
        "commercial_properties_coming": "¡La función de Propiedades Comerciales estará disponible próximamente!",
        "land_plots": "Terrenos y Parcelas",
        "land_plots_desc": "Terrenos Residenciales, Comerciales, Tierras Agrícolas",
        "land_plots_coming": "¡La función de Terrenos y Parcelas estará disponible próximamente!",
        "appointment_booked_notification": "Cita reservada para {date}: {desc}"
    },
    "hi": {
        "welcome": "RentArena जीरो ब्रोकरेज रेंटल में आपका स्वागत है",
        "tagline": "दलाल को छोड़ें। शून्य ब्रोकरेज शुल्क के साथ सीधे मालिक की संपत्तियों को किराए पर लें।",
        "apartment_not_found": "आईडी {id} वाला अपार्टमेंट नहीं मिला।",
        "building_not_found": "आईडी {id} वाली इमारत नहीं मिली।",
        "occupancy_rate_title": "अधिभोग और किराया विश्लेषण",
        "total_apartments": "कुल अपार्टमेंट",
        "occupied_apartments": "भरे हुए अपार्टमेंट",
        "vacant_apartments": "खाली अपार्टमेंट",
        "occupancy_rate": "अधिभोग दर",
        "success": "अनुरोध सफलतापूर्वक पूरा हुआ",
        "summary": "यह रिपोर्ट कुल अपार्टमेंट की सूची दिखाती है, भरे हुए बनाम खाली इकाइयों को उजागर करती है, और बिना किसी दलाली शुल्क के समग्र अधिभोग दर की गणना करती है।",
        "owner_login": "मालिक लॉगिन",
        "manager_login": "संपत्ति प्रबंधक लॉगिन",
        "tenant_login": "किराएदार लॉगिन",
        "owner_reg": "मालिक पंजीकरण",
        "tenant_reg": "किराएदार पंजीकरण",
        "dashboard": "डैशबोर्ड",
        "logout": "लॉगआउट",
        "buildings": "इमारतें",
        "apartments": "अपार्टमेंट",
        "tenants": "किराएदार",
        "managers": "संपत्ति प्रबंधक",
        "messages": "संदेश",
        "events": "घटनाक्रम",
        "appointments": "अपॉइंटमेंट",
        "profile": "प्रोफ़ाइल",
        "actions": "कार्रवाइयाँ",
        "edit": "संपादित करें",
        "delete": "हटाएं",
        "create": "बनाएं",
        "save": "सहेजें",
        "cancel": "रद्द करें",
        "loading": "लोड हो रहा है...",
        "no_records": "कोई रिकॉर्ड नहीं मिला।",
        "email": "ईमेल",
        "password": "पासवर्ड",
        "phone": "फ़ोन नंबर",
        "name": "नाम",
        "address": "पता",
        "city": "शहर",
        "province": "राज्य",
        "postal_code": "पिन कोड",
        "price": "किराया",
        "rooms": "कमरे",
        "status": "स्थिति",
        "description": "विवरण",
        "date": "दिनांक",
        "apartment_card_desc": "सीधे मालिक के अपार्टमेंट ब्राउज़ करें और खोजें।",
        "apartments_flats": "अपार्टमेंट और फ्लैट्स",
        "apartments_flats_desc": "1BHK, 2BHK, 3BHK, स्टूडियो अपार्टमेंट",
        "independent_houses": "स्वतंत्र घर और विला",
        "independent_houses_desc": "विला, डुप्लेक्स, रो हाउस, स्वतंत्र घर",
        "independent_houses_coming": "स्वतंत्र घर और विला सुविधा जल्द ही आ रही है!",
        "commercial_properties": "व्यावसायिक संपत्तियां",
        "commercial_properties_desc": "कार्यालय, दुकानें, शोरूम, को-वर्किंग स्पेस",
        "commercial_properties_coming": "व्यावसायिक संपत्तियां सुविधा जल्द ही आ रही है!",
        "land_plots": "भूमि और प्लॉट",
        "land_plots_desc": "आवासीय भूखंड, व्यावसायिक भूखंड, कृषि भूमि",
        "land_plots_coming": "भूमि और प्लॉट सुविधा जल्द ही आ रही है!",
        "appointment_booked_notification": "{date} के लिए अपॉइंटमेंट बुक किया गया: {desc}"
    }
};

function getLocaleFromHeader(acceptLanguage) {
    if (!acceptLanguage) return "en";
    const languages = acceptLanguage.split(',').map(lang => lang.split(';')[0].split('-')[0].trim().toLowerCase());
    for (const lang of languages) {
        if (TRANSLATIONS[lang]) return lang;
    }
    return "en";
}

function translate(key, lang, replacements = {}) {
    const localeDict = TRANSLATIONS[lang] || TRANSLATIONS["en"];
    let messageTmpl = localeDict[key] || TRANSLATIONS["en"][key] || key;
    for (const [k, v] of Object.entries(replacements)) {
        messageTmpl = messageTmpl.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
    }
    return messageTmpl;
}

module.exports = {
    TRANSLATIONS,
    getLocaleFromHeader,
    translate
};
